import { BossRushBossDefinition } from './BossRushTypes';

export const BOSS_RUSH_BOSSES: BossRushBossDefinition[] = [
  {
    index: 1,
    key: 'gatekeeper',
    name: 'The Gatekeeper',
    subtitle: 'Introductory pattern boss',
    color: '#ef4444',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4250 },
    radius: 180,
    maxHealth: 76000,
    contactDamage: 118,
    moveStyle: 'ANCHOR',
    transformSeconds: 2.6,
    introSeconds: 1.4,
    awakeningSeconds: 2.15,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.4,
    recoveryReductionMultiplier: 0.74,
    postAwakenRecovery: 0.34,
    phases: 2,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 2.1, recovery: 0.54, maxRange: 2800, weight: 0.72 },
      { id: 'gate_lane', label: 'Lane Slam', cooldown: 3.9, recovery: 1.02, maxRange: 2400, weight: 1.25 },
      { id: 'gate_arc_beam', label: 'Arc Beam', cooldown: 6.5, recovery: 1.34, maxRange: 2800, weight: 1.16 },
      { id: 'gate_squares', label: 'Square Burst', cooldown: 5.5, recovery: 1.12, maxRange: 2600, weight: 1.08 },
      { id: 'gate_hash_lock', label: 'Hash Lock', cooldown: 6.2, recovery: 1.18, maxRange: 2600, weight: 1.1 },
      { id: 'gate_cross_grid', label: 'Vault Crossfire', cooldown: 7.4, recovery: 1.24, maxRange: 2500, phases: [2], weight: 0.98 },
      { id: 'gate_rapid_crosshatch', label: 'Rapid Crosshatch', cooldown: 8.2, recovery: 1.4, maxRange: 2600, phases: [2], weight: 1.02 },
      { id: 'gate_dash', label: 'Dash Line', cooldown: 7.1, recovery: 1.28, minRange: 320, maxRange: 2200, phases: [2], weight: 1.02 },
      { id: 'gate_ring_prison', label: 'Ring Prison', cooldown: 8.1, recovery: 1.18, maxRange: 2200, phases: [2], weight: 1.02 },
    ],
  },
  {
    index: 2,
    key: 'splitter',
    name: 'The Splitter',
    subtitle: 'Multi-angle pressure boss',
    color: '#fb7185',
    accent: '#fecdd3',
    arenaAnchor: { x: 5000, y: 4200 },
    radius: 188,
    maxHealth: 108000,
    contactDamage: 128,
    moveStyle: 'STRAFE',
    transformSeconds: 2.9,
    introSeconds: 1.55,
    awakeningSeconds: 2.3,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.46,
    recoveryReductionMultiplier: 0.72,
    postAwakenRecovery: 0.38,
    phases: 2,
    archetype: 'SWARMLORD',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.95, recovery: 0.52, maxRange: 2900, weight: 0.74 },
      { id: 'splitter_triple_lane', label: 'Triple Lane', cooldown: 4.1, recovery: 1.06, maxRange: 2600, weight: 1.24 },
      { id: 'splitter_checker', label: 'Checkerboard', cooldown: 6.1, recovery: 1.14, maxRange: 2200, weight: 1.08 },
      { id: 'splitter_zigzag_lines', label: 'Corrupted Zigzag', cooldown: 6.6, recovery: 1.28, maxRange: 2800, phases: [2], weight: 1.14 },
      { id: 'splitter_cone', label: 'Cone Sweep', cooldown: 5.1, recovery: 1.02, minRange: 240, maxRange: 1800, phases: [2], weight: 1.02 },
      { id: 'splitter_corrupted_cascade', label: 'Corrupted Cascade', cooldown: 8.9, recovery: 1.42, maxRange: 2800, phases: [2], weight: 0.98 },
      { id: 'splitter_pincer', label: 'Pincer Collapse', cooldown: 7.8, recovery: 1.2, maxRange: 2400, phases: [2], weight: 1 },
    ],
  },
  {
    index: 3,
    key: 'reactor',
    name: 'The Reactor',
    subtitle: 'Arena-control boss',
    color: '#f97316',
    accent: '#fdba74',
    arenaAnchor: { x: 5000, y: 4150 },
    radius: 194,
    maxHealth: 146000,
    contactDamage: 136,
    moveStyle: 'ORBIT',
    transformSeconds: 3.1,
    introSeconds: 1.7,
    awakeningSeconds: 2.55,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.52,
    recoveryReductionMultiplier: 0.68,
    postAwakenRecovery: 0.48,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.9, recovery: 0.5, maxRange: 3000, weight: 0.68 },
      { id: 'reactor_circles', label: 'Impact Circles', cooldown: 4.8, recovery: 1.04, maxRange: 2600, weight: 1.12 },
      { id: 'reactor_arc', label: 'Rotating Arc', cooldown: 5.9, recovery: 1.16, maxRange: 2200, phases: [2, 3], weight: 1.08 },
      { id: 'reactor_shuffle', label: 'Safe-Zone Shuffle', cooldown: 8.0, recovery: 1.28, phases: [3], weight: 0.98 },
      { id: 'reactor_supernova', label: 'Supernova', cooldown: 9.3, recovery: 1.46, phases: [3], weight: 0.92 },
    ],
  },
  {
    index: 4,
    key: 'executioner',
    name: 'The Executioner',
    subtitle: 'Heavy punishment boss',
    color: '#dc2626',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4100 },
    radius: 205,
    maxHealth: 194000,
    contactDamage: 148,
    moveStyle: 'EXECUTION',
    transformSeconds: 3.35,
    introSeconds: 1.85,
    awakeningSeconds: 2.75,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.6,
    recoveryReductionMultiplier: 0.64,
    postAwakenRecovery: 0.56,
    phases: 3,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.82, recovery: 0.48, maxRange: 3100, weight: 0.66 },
      { id: 'executioner_cleave', label: 'Massive Cleave', cooldown: 5.1, recovery: 1.18, maxRange: 2800, weight: 1.22 },
      { id: 'executioner_lockon', label: 'Lock-On Burst', cooldown: 6.0, recovery: 1.06, maxRange: 2600, weight: 1.08 },
      { id: 'executioner_cross', label: 'Cross Strike', cooldown: 7.5, recovery: 1.28, phases: [2, 3], weight: 1.02 },
      { id: 'executioner_fan_drive', label: 'Fan Drive', cooldown: 8.0, recovery: 1.34, phases: [3], weight: 0.98 },
    ],
  },
  {
    index: 5,
    key: 'grand_singularity',
    name: 'The Grand Singularity',
    subtitle: 'Final boss',
    color: '#7c3aed',
    accent: '#c4b5fd',
    arenaAnchor: { x: 5000, y: 4050 },
    radius: 220,
    maxHealth: 286000,
    contactDamage: 168,
    moveStyle: 'SINGULARITY',
    transformSeconds: 3.8,
    introSeconds: 2.1,
    awakeningSeconds: 3.15,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.55,
    attackFrequencyMultiplier: 1.72,
    recoveryReductionMultiplier: 0.58,
    postAwakenRecovery: 0.68,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.78, recovery: 0.46, maxRange: 3200, weight: 0.64 },
      { id: 'singularity_lane_chain', label: 'Lane Chain', cooldown: 4.8, recovery: 1.02, maxRange: 3200, weight: 1.18 },
      { id: 'singularity_gravity', label: 'Gravity Trap', cooldown: 7.1, recovery: 1.22, maxRange: 2600, phases: [2, 3], weight: 1.08 },
      { id: 'singularity_spiral', label: 'Spiral Barrage', cooldown: 7.8, recovery: 1.18, maxRange: 2600, phases: [2, 3], weight: 1.04 },
      { id: 'singularity_rapid_chain', label: 'Rapid Chain', cooldown: 8.8, recovery: 1.42, phases: [3], weight: 0.98 },
      { id: 'singularity_event_horizon', label: 'Event Horizon', cooldown: 10.0, recovery: 1.55, phases: [3], weight: 0.9 },
    ],
  },
];
