import { BossRushBossDefinition } from './BossRushTypes';

export const BOSS_RUSH_BOSSES: BossRushBossDefinition[] = [
  {
    index: 1,
    key: 'gatekeeper',
    name: 'The Gatekeeper',
    subtitle: 'Introductory pattern boss',
    color: '#ef4444',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4250 },
    radius: 180,
    maxHealth: 64000,
    contactDamage: 105,
    moveStyle: 'ANCHOR',
    introSeconds: 1.4,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.28,
    recoveryReductionMultiplier: 0.82,
    phases: 2,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'gate_lane', label: 'Lane Slam', cooldown: 4.3, recovery: 1.15, maxRange: 2400, weight: 1.2 },
      { id: 'gate_squares', label: 'Square Burst', cooldown: 6.2, recovery: 1.25, maxRange: 2600, weight: 1 },
      { id: 'gate_dash', label: 'Dash Line', cooldown: 8.2, recovery: 1.55, minRange: 320, maxRange: 2200, phases: [2], weight: 0.9 },
    ],
  },
  {
    index: 2,
    key: 'splitter',
    name: 'The Splitter',
    subtitle: 'Multi-angle pressure boss',
    color: '#fb7185',
    accent: '#fecdd3',
    arenaAnchor: { x: 5000, y: 4200 },
    radius: 188,
    maxHealth: 92000,
    contactDamage: 118,
    moveStyle: 'STRAFE',
    introSeconds: 1.55,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.34,
    recoveryReductionMultiplier: 0.8,
    phases: 2,
    archetype: 'SWARMLORD',
    attacks: [
      { id: 'splitter_triple_lane', label: 'Triple Lane', cooldown: 4.6, recovery: 1.2, maxRange: 2600, weight: 1.2 },
      { id: 'splitter_checker', label: 'Checkerboard', cooldown: 6.8, recovery: 1.3, maxRange: 2200, weight: 1.05 },
      { id: 'splitter_cone', label: 'Cone Sweep', cooldown: 5.8, recovery: 1.15, minRange: 240, maxRange: 1800, phases: [2], weight: 1 },
    ],
  },
  {
    index: 3,
    key: 'reactor',
    name: 'The Reactor',
    subtitle: 'Arena-control boss',
    color: '#f97316',
    accent: '#fdba74',
    arenaAnchor: { x: 5000, y: 4150 },
    radius: 194,
    maxHealth: 126000,
    contactDamage: 126,
    moveStyle: 'ORBIT',
    introSeconds: 1.7,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.38,
    recoveryReductionMultiplier: 0.78,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'reactor_circles', label: 'Impact Circles', cooldown: 5.2, recovery: 1.15, maxRange: 2600, weight: 1.1 },
      { id: 'reactor_arc', label: 'Rotating Arc', cooldown: 6.4, recovery: 1.3, maxRange: 2200, phases: [2, 3], weight: 1.05 },
      { id: 'reactor_shuffle', label: 'Safe-Zone Shuffle', cooldown: 8.8, recovery: 1.45, phases: [3], weight: 0.95 },
    ],
  },
  {
    index: 4,
    key: 'executioner',
    name: 'The Executioner',
    subtitle: 'Heavy punishment boss',
    color: '#dc2626',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4100 },
    radius: 205,
    maxHealth: 168000,
    contactDamage: 138,
    moveStyle: 'EXECUTION',
    introSeconds: 1.85,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.46,
    recoveryReductionMultiplier: 0.74,
    phases: 3,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'executioner_cleave', label: 'Massive Cleave', cooldown: 5.8, recovery: 1.35, maxRange: 2800, weight: 1.2 },
      { id: 'executioner_lockon', label: 'Lock-On Burst', cooldown: 6.6, recovery: 1.2, maxRange: 2600, weight: 1.05 },
      { id: 'executioner_cross', label: 'Cross Strike', cooldown: 8.4, recovery: 1.45, phases: [2, 3], weight: 1 },
    ],
  },
  {
    index: 5,
    key: 'grand_singularity',
    name: 'The Grand Singularity',
    subtitle: 'Final boss',
    color: '#7c3aed',
    accent: '#c4b5fd',
    arenaAnchor: { x: 5000, y: 4050 },
    radius: 220,
    maxHealth: 248000,
    contactDamage: 154,
    moveStyle: 'SINGULARITY',
    introSeconds: 2.1,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.55,
    attackFrequencyMultiplier: 1.55,
    recoveryReductionMultiplier: 0.7,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'singularity_lane_chain', label: 'Lane Chain', cooldown: 5.2, recovery: 1.15, maxRange: 3200, weight: 1.15 },
      { id: 'singularity_gravity', label: 'Gravity Trap', cooldown: 7.8, recovery: 1.4, maxRange: 2600, phases: [2, 3], weight: 1.05 },
      { id: 'singularity_spiral', label: 'Spiral Barrage', cooldown: 8.4, recovery: 1.35, maxRange: 2600, phases: [2, 3], weight: 1 },
      { id: 'singularity_rapid_chain', label: 'Rapid Chain', cooldown: 9.4, recovery: 1.6, phases: [3], weight: 0.95 },
    ],
  },
];
