import { BossRushBossDefinition } from './BossRushTypes';

export const BOSS_RUSH_BOSSES: BossRushBossDefinition[] = [
  {
    index: 1,
    key: 'gatekeeper',
    name: 'Aegis Gatekeeper',
    subtitle: 'Vault sentinel of the first seal',
    color: '#ef4444',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4250 },
    radius: 180,
    maxHealth: 76000,
    contactDamage: 118,
    moveStyle: 'ANCHOR',
    transformSeconds: 2.6,
    introSeconds: 1.4,
    awakeningSeconds: 2.15,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.28,
    recoveryReductionMultiplier: 0.86,
    postAwakenRecovery: 0.54,
    phases: 2,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.7, recovery: 0.46, maxRange: 2800, weight: 0.76 },
      { id: 'gate_lane', label: 'Lane Slam', cooldown: 3.35, recovery: 0.9, maxRange: 2400, weight: 1.25 },
      { id: 'gate_arc_beam', label: 'Arc Beam', cooldown: 9.8, recovery: 3.45, maxRange: 2800, weight: 1.14, allowComboFollowup: false },
      { id: 'gate_squares', label: 'Square Burst', cooldown: 4.95, recovery: 0.98, maxRange: 2600, weight: 1.08 },
      { id: 'gate_corner_crush', label: 'Corner Crush', cooldown: 6.4, recovery: 1.06, maxRange: 2400, weight: 1.02 },
      { id: 'gate_hash_lock', label: 'Hash Lock', cooldown: 5.5, recovery: 1.02, maxRange: 2600, weight: 1.1 },
      { id: 'gate_cross_grid', label: 'Vault Crossfire', cooldown: 7.8, recovery: 1.3, maxRange: 2500, phases: [2], weight: 0.88 },
      { id: 'gate_rapid_crosshatch', label: 'Rapid Crosshatch', cooldown: 8.8, recovery: 1.5, maxRange: 2600, phases: [2], weight: 0.86 },
      { id: 'gate_dash', label: 'Dash Line', cooldown: 8.6, recovery: 1.52, minRange: 320, maxRange: 2200, phases: [2], weight: 0.72 },
      { id: 'gate_ring_prison', label: 'Ring Prison', cooldown: 9.4, recovery: 1.54, maxRange: 2200, phases: [2], weight: 0.74 },
    ],
  },
  {
    index: 2,
    key: 'splitter',
    name: 'Vanta Splitter',
    subtitle: 'Linebreaker of fractured angles',
    color: '#fb7185',
    accent: '#fecdd3',
    arenaAnchor: { x: 5000, y: 4200 },
    radius: 188,
    maxHealth: 108000,
    contactDamage: 128,
    moveStyle: 'STRAFE',
    transformSeconds: 2.9,
    introSeconds: 1.55,
    awakeningSeconds: 2.3,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.5,
    attackFrequencyMultiplier: 1.58,
    recoveryReductionMultiplier: 0.66,
    postAwakenRecovery: 0.3,
    phases: 2,
    archetype: 'SWARMLORD',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.55, recovery: 0.44, maxRange: 2900, weight: 0.78 },
      { id: 'splitter_triple_lane', label: 'Triple Lane', cooldown: 3.55, recovery: 0.94, maxRange: 2600, weight: 1.26 },
      { id: 'splitter_checker', label: 'Checkerboard', cooldown: 5.35, recovery: 1.02, maxRange: 2200, weight: 1.1 },
      { id: 'splitter_zigzag_lines', label: 'Corrupted Zigzag', cooldown: 5.75, recovery: 1.1, maxRange: 2800, phases: [2], weight: 1.18 },
      { id: 'splitter_cone', label: 'Cone Sweep', cooldown: 4.45, recovery: 0.9, minRange: 240, maxRange: 1800, phases: [2], weight: 1.06 },
      { id: 'splitter_corrupted_cascade', label: 'Corrupted Cascade', cooldown: 7.6, recovery: 1.22, maxRange: 2800, phases: [2], weight: 1.02 },
      { id: 'splitter_pincer', label: 'Z Collapse', cooldown: 6.85, recovery: 1.02, maxRange: 2400, phases: [2], weight: 1.04 },
      { id: 'splitter_x_spread', label: 'X Spread', cooldown: 5.9, recovery: 0.96, maxRange: 2600, weight: 1.08 },
      { id: 'splitter_orbit_minefield', label: 'Orbit Minefield', cooldown: 6.4, recovery: 1.04, maxRange: 2200, phases: [2], weight: 1.1 },
      { id: 'splitter_tripwire_lattice', label: 'Tripwire Lattice', cooldown: 7.2, recovery: 1.08, maxRange: 2600, phases: [2], weight: 1.08 },
    ],
  },
  {
    index: 3,
    key: 'reactor',
    name: 'Pyre Reactor',
    subtitle: 'Core tyrant of radiant collapse',
    color: '#f97316',
    accent: '#fdba74',
    arenaAnchor: { x: 5000, y: 4150 },
    radius: 194,
    maxHealth: 146000,
    contactDamage: 136,
    moveStyle: 'ORBIT',
    transformSeconds: 3.1,
    introSeconds: 1.7,
    awakeningSeconds: 2.55,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.66,
    recoveryReductionMultiplier: 0.61,
    postAwakenRecovery: 0.4,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.48, recovery: 0.42, maxRange: 3000, weight: 0.74 },
      { id: 'reactor_circles', label: 'Impact Circles', cooldown: 4.05, recovery: 0.92, maxRange: 2600, weight: 1.14 },
      { id: 'reactor_arc', label: 'Rotating Arc', cooldown: 5.0, recovery: 1.0, maxRange: 2200, phases: [2, 3], weight: 1.12 },
      { id: 'reactor_quadrant_blast', label: 'Quadrant Blast', cooldown: 5.25, recovery: 0.98, maxRange: 2400, phases: [2, 3], weight: 1.06 },
      { id: 'reactor_lane_lattice', label: 'Lane Lattice', cooldown: 6.1, recovery: 1.04, maxRange: 3000, phases: [2, 3], weight: 1.08 },
      { id: 'reactor_shuffle', label: 'O Core', cooldown: 6.8, recovery: 1.12, phases: [3], weight: 1.02 },
      { id: 'reactor_orbit_crush', label: 'Orbit Crush', cooldown: 7.2, recovery: 1.12, phases: [3], weight: 1.04, allowComboFollowup: false },
      { id: 'reactor_meltdown_steps', label: 'Meltdown Steps', cooldown: 5.45, recovery: 0.96, maxRange: 2600, phases: [2, 3], weight: 1.1 },
      { id: 'reactor_supernova', label: 'Supernova', cooldown: 8.0, recovery: 1.26, phases: [3], weight: 0.96, allowComboFollowup: false },
      { id: 'reactor_blood_crescent', label: 'Blood Crescent', cooldown: 8.7, recovery: 2.9, maxRange: 2800, phases: [2, 3], weight: 0.94, allowComboFollowup: false },
    ],
  },
  {
    index: 4,
    key: 'executioner',
    name: 'Iron Executioner',
    subtitle: 'Judgement engine of the gauntlet',
    color: '#dc2626',
    accent: '#fca5a5',
    arenaAnchor: { x: 5000, y: 4100 },
    radius: 205,
    maxHealth: 194000,
    contactDamage: 148,
    moveStyle: 'EXECUTION',
    transformSeconds: 3.35,
    introSeconds: 1.85,
    awakeningSeconds: 2.75,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.52,
    attackFrequencyMultiplier: 1.74,
    recoveryReductionMultiplier: 0.56,
    postAwakenRecovery: 0.44,
    phases: 3,
    archetype: 'SIEGEBREAKER',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.42, recovery: 0.4, maxRange: 3100, weight: 0.72 },
      { id: 'executioner_cleave', label: 'Massive Cleave', cooldown: 4.35, recovery: 1.02, maxRange: 2800, weight: 1.24 },
      { id: 'executioner_lockon', label: 'L Verdict', cooldown: 5.2, recovery: 0.94, maxRange: 2600, weight: 1.12 },
      { id: 'executioner_judgement_ring', label: 'Judgement Ring', cooldown: 5.8, recovery: 1.02, maxRange: 2400, phases: [2, 3], weight: 1.08 },
      { id: 'executioner_box_cleave', label: 'Box Cleave', cooldown: 6.25, recovery: 1.06, maxRange: 2200, phases: [2, 3], weight: 1.08 },
      { id: 'executioner_cross', label: 'X Strike', cooldown: 7.5, recovery: 2.2, phases: [2, 3], weight: 1.02, allowComboFollowup: false },
      { id: 'executioner_falling_axes', label: 'Falling Axes', cooldown: 6.5, recovery: 1.02, maxRange: 3000, phases: [2, 3], weight: 1.06 },
      { id: 'executioner_pursuit_lines', label: 'Pursuit Lines', cooldown: 4.95, recovery: 0.92, maxRange: 2600, phases: [2, 3], weight: 1.1 },
      { id: 'executioner_corner_purge', label: 'Corner Purge', cooldown: 7.1, recovery: 1.16, maxRange: 2200, phases: [3], weight: 1.04, allowComboFollowup: false },
      { id: 'executioner_fan_drive', label: 'Fan Drive', cooldown: 6.95, recovery: 1.12, phases: [3], weight: 1.02 },
    ],
  },
  {
    index: 5,
    key: 'grand_singularity',
    name: 'The Grand Singularity',
    subtitle: 'Apex void sovereign',
    color: '#7c3aed',
    accent: '#c4b5fd',
    arenaAnchor: { x: 5000, y: 4050 },
    radius: 220,
    maxHealth: 286000,
    contactDamage: 168,
    moveStyle: 'SINGULARITY',
    transformSeconds: 3.8,
    introSeconds: 2.1,
    awakeningSeconds: 3.15,
    awakenThreshold: 0.3,
    awakenRestoreRatio: 0.55,
    attackFrequencyMultiplier: 1.92,
    recoveryReductionMultiplier: 0.5,
    postAwakenRecovery: 0.5,
    phases: 3,
    archetype: 'SINGULARITY',
    attacks: [
      { id: 'boss_basic_volley', label: 'Suppressive Volley', cooldown: 1.34, recovery: 0.36, maxRange: 3200, weight: 0.7 },
      { id: 'singularity_lane_chain', label: 'Lane Chain', cooldown: 4.0, recovery: 0.9, maxRange: 3200, weight: 1.22 },
      { id: 'singularity_gravity', label: 'Gravity Trap', cooldown: 6.0, recovery: 1.06, maxRange: 2600, phases: [2, 3], weight: 1.12 },
      { id: 'singularity_spiral', label: 'Spiral Barrage', cooldown: 6.6, recovery: 1.02, maxRange: 2600, phases: [2, 3], weight: 1.08 },
      { id: 'singularity_cross_maze', label: 'Cross Maze', cooldown: 5.75, recovery: 1.0, maxRange: 3000, phases: [2, 3], weight: 1.08 },
      { id: 'singularity_orbit_seal', label: 'Orbit Seal', cooldown: 6.8, recovery: 1.08, maxRange: 2400, phases: [2, 3], weight: 1.08, allowComboFollowup: false },
      { id: 'singularity_gravity_grid', label: 'Gravity Grid', cooldown: 7.2, recovery: 1.14, phases: [3], weight: 1.04, allowComboFollowup: false },
      { id: 'singularity_starfall', label: 'Starfall', cooldown: 5.6, recovery: 0.98, maxRange: 2600, phases: [2, 3], weight: 1.1 },
      { id: 'singularity_rapid_chain', label: 'Z Collapse', cooldown: 7.4, recovery: 1.22, phases: [3], weight: 1.02, allowComboFollowup: false },
      { id: 'singularity_event_horizon', label: 'Event Horizon O', cooldown: 8.6, recovery: 1.34, phases: [3], weight: 0.96, allowComboFollowup: false },
    ],
  },
];
